using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.3.10297.227")]
[assembly: AssemblyInformationalVersionAttribute("1.3.10297.227")]
[assembly: AssemblyConfigurationAttribute("release")]

